"""Centralized constants for the MX-CARD Agent project.

Import from sub-modules or directly from this package:
    from constants import DEFAULT_MODEL_NAME, BLOCKED_COMMANDS, APP_NAME
    from constants.tools import READ_FILE_MAX_SIZE
"""

from constants.models import (
    DEFAULT_MODEL_NAME,
    DEFAULT_TEMPERATURE,
    MIN_TEMPERATURE,
    MAX_TEMPERATURE,
    DEFAULT_CONTEXT_WINDOW,
    CONTEXT_COMPRESSION_RATIO,
    LLM_MAX_RETRIES,
    DEFAULT_TOKENIZER_ENCODING,
    DEFAULT_TOKEN_MODEL,
)

from constants.tools import (
    READ_FILE_MAX_SIZE,
    READ_FILE_MAX_OUTPUT_TOKENS,
    SHELL_DEFAULT_TIMEOUT,
    SHELL_MIN_TIMEOUT,
    SHELL_MAX_TIMEOUT,
    SHELL_OUTPUT_MAX_BYTES,
    BLOCKED_COMMANDS,
    WEB_SEARCH_DEFAULT_MAX_RESULTS,
    WEB_SEARCH_MIN_RESULTS,
    WEB_SEARCH_MAX_RESULTS,
    WEB_SEARCH_REGION,
    WEB_SEARCH_SAFESEARCH,
    WEB_SEARCH_TIMELIMIT,
    WEB_FETCH_DEFAULT_TIMEOUT,
    WEB_FETCH_MIN_TIMEOUT,
    WEB_FETCH_MAX_TIMEOUT,
    WEB_FETCH_MAX_CONTENT_BYTES,
    GREP_MAX_FILES,
    GLOB_MAX_RESULTS,
    DIR_SCAN_EXCLUDES,
    TOOL_ARG_PREFERRED_ORDER,
    FILE_EXTENSION_LANGUAGE_MAP,
)

from constants.safety import (
    SHELL_ENV_DEFAULT_EXCLUDE_PATTERNS,
    DANGEROUS_COMMAND_PATTERNS,
    SAFE_COMMAND_PATTERNS,
    HOOK_DEFAULT_TIMEOUT_SEC,
    MCP_DEFAULT_STARTUP_TIMEOUT_SEC,
)

from constants.agent import (
    DEFAULT_MAX_TURNS,
    PRUNE_PROTECT_TOKENS,
    PRUNE_MINIMUM_TOKENS,
    PRUNED_CONTENT_PLACEHOLDER,
    LOOP_MAX_EXACT_REPEATS,
    LOOP_MAX_CYCLE_LENGTH,
    LOOP_HISTORY_MAX_LENGTH,
    SUBAGENT_DEFAULT_MAX_TURNS,
    SUBAGENT_DEFAULT_TIMEOUT_SECONDS,
    SUBAGENT_INVESTIGATOR_MAX_TURNS,
    SUBAGENT_INVESTIGATOR_TIMEOUT,
    SUBAGENT_REVIEWER_MAX_TURNS,
    SUBAGENT_REVIEWER_TIMEOUT,
    COMPACTION_TOOL_OUTPUT_TRUNCATE,
    COMPACTION_ASSISTANT_TRUNCATE,
    COMPACTION_USER_TRUNCATE,
    COMPACTION_TOOL_ARGS_TRUNCATE,
    FILE_PERMISSION_DIR,
    FILE_PERMISSION_FILE,
)

from constants.app import (
    APP_NAME,
    APP_DIR_NAME,
    APP_PROJECT_DIR,
    CONFIG_FILE_NAME,
    AGENT_MD_FILE,
    MEMORY_FILE_NAME,
    SESSIONS_DIR_NAME,
    CHECKPOINTS_DIR_NAME,
    CHECKPOINT_TIMESTAMP_FORMAT,
    ENV_API_KEY,
    ENV_BASE_URL,
)

from constants.ui import (
    TUI_MAX_BLOCK_TOKENS,
    AGENT_THEME,
    WELCOME_COMMANDS,
)
