"""Constants related to agent behavior, loop detection, and context management."""

# Agent max turns
DEFAULT_MAX_TURNS = 100

# Context pruning thresholds
PRUNE_PROTECT_TOKENS = 40_000
PRUNE_MINIMUM_TOKENS = 20_000
PRUNED_CONTENT_PLACEHOLDER = "[Old tool result content cleared]"

# Loop detection
LOOP_MAX_EXACT_REPEATS = 3
LOOP_MAX_CYCLE_LENGTH = 3
LOOP_HISTORY_MAX_LENGTH = 20

# Subagent defaults
SUBAGENT_DEFAULT_MAX_TURNS = 20
SUBAGENT_DEFAULT_TIMEOUT_SECONDS = 600
SUBAGENT_INVESTIGATOR_MAX_TURNS = 20
SUBAGENT_INVESTIGATOR_TIMEOUT = 600
SUBAGENT_REVIEWER_MAX_TURNS = 10
SUBAGENT_REVIEWER_TIMEOUT = 300

# Compaction truncation limits (characters)
COMPACTION_TOOL_OUTPUT_TRUNCATE = 2000
COMPACTION_ASSISTANT_TRUNCATE = 3000
COMPACTION_USER_TRUNCATE = 1500
COMPACTION_TOOL_ARGS_TRUNCATE = 500

# File permissions (Unix)
FILE_PERMISSION_DIR = 0o700
FILE_PERMISSION_FILE = 0o600
