hooks_enabled = false

[model]
temperature = 0

[[hooks]]
name='test_before_tool'
trigger='before_tool'
command='python ./scripts/test_tool.py'
enabled = false

[[hooks]]
name='test_before_agent'
trigger='before_agent'
command='python ./scripts/test_tool.py'
enabled = false

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", ".", "/tmp"]